# Generated by Django 5.0 on 2024-01-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('signature', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
