# Generated by Django 5.0 on 2024-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpersons',
            name='signed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
