# Generated by Django 5.0 on 2024-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davaorequestitems',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
