# Generated by Django 5.0 on 2024-02-09 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0002_davaorequestitems_ignore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davaorequestheader',
            name='project',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
