# Generated by Django 5.0 on 2024-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0002_alter_davaorequestitems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davaorequestheader',
            name='payee',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
