# Generated by Django 5.0 on 2024-01-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0002_authorizedpersons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizedpersons',
            old_name='role',
            new_name='title',
        ),
    ]
