# Generated by Django 5.0 on 2024-02-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0003_authorizedpersons_personnel'),
        ('main', '0005_remove_personnel_personnel_name_title_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedpersons',
            name='name',
            field=models.CharField(blank=True, max_length=53, null=True),
        ),
        migrations.AlterField(
            model_name='authorizedpersons',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.personnel'),
        ),
        migrations.AlterField(
            model_name='authorizedpersons',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
