# Generated by Django 5.0 on 2024-01-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0003_rename_role_authorizedpersons_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpersons',
            name='header',
            field=models.ForeignKey(default='DVO2024-001', on_delete=django.db.models.deletion.CASCADE, to='davao_requests.davaorequestheader'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='davaorequestitems',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='davaorequestitems',
            name='header',
            field=models.ForeignKey(default='DVO2024-0001', on_delete=django.db.models.deletion.CASCADE, to='davao_requests.davaorequestheader'),
        ),
    ]
