# Generated by Django 5.0 on 2024-01-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0004_authorizedpersons_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davaorequestitems',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='davao_requests.davaorequestheader'),
        ),
    ]
