# Generated by Django 5.0 on 2024-02-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0005_davaorequestheader_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signatures/'),
        ),
    ]
