# Generated by Django 5.0 on 2024-01-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0005_alter_davaorequestitems_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedpersons',
            name='middle_initial',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
