# Generated by Django 5.0 on 2024-02-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0006_persons_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
