# Generated by Django 5.0 on 2024-02-20 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0007_delete_persons'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpersons',
            name='personnel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.personnel'),
            preserve_default=False,
        ),
    ]
