# Generated by Django 5.0 on 2024-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0008_authorizedpersons_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedpersons',
            name='signature',
        ),
        migrations.AddField(
            model_name='authorizedpersons',
            name='sign',
            field=models.BooleanField(default=False),
        ),
    ]
