# Generated by Django 5.0 on 2024-02-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0009_remove_authorizedpersons_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpersons',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signatures/'),
        ),
    ]
