# Generated by Django 5.0 on 2024-02-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davao_requests', '0010_authorizedpersons_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedpersons',
            name='signature',
        ),
    ]
