# Generated by Django 5.0 on 2024-02-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotabato_requests', '0005_alter_cotabatorequestheader_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotabatorequestheader',
            name='note',
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
    ]
