# Generated by Django 5.0 on 2024-02-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotabato_requests', '0006_cotabatorequestheader_note'),
        ('main', '0005_remove_personnel_personnel_name_title_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpersons',
            name='personnel',
            field=models.ManyToManyField(to='main.personnel'),
        ),
        migrations.AddField(
            model_name='authorizedpersons',
            name='signed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='authorizedpersons',
            name='name',
            field=models.CharField(blank=True, max_length=53, null=True),
        ),
        migrations.AlterField(
            model_name='authorizedpersons',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
