# Generated by Django 5.0 on 2023-12-28 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurigaoRequestHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rs_number', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=200)),
                ('payee', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=100)),
                ('urgent', models.BooleanField()),
                ('date_requested', models.DateField()),
                ('date_needed', models.DateField()),
                ('last_modified', models.DateField(auto_now_add=True)),
                ('created', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurigaoRequestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('unit_cost', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('served', models.BooleanField()),
                ('rs_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surigao_requests.surigaorequestheader')),
            ],
        ),
    ]
