# Generated by Django 5.0 on 2024-02-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_personnel_personnel_name_title_uniq'),
        ('surigao_requests', '0004_surigaorequestheader_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpersons',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuthorizedPersonsSurigao', to='main.personnel'),
        ),
        migrations.AddField(
            model_name='authorizedpersons',
            name='signed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='authorizedpersons',
            name='name',
            field=models.CharField(blank=True, max_length=53, null=True),
        ),
        migrations.AlterField(
            model_name='authorizedpersons',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
