# Generated by Django 5.0 on 2024-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signatures/personnel/'),
        ),
    ]
