# Generated by Django 5.0 on 2024-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_personnel_signature'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.UniqueConstraint(fields=('name', 'title'), name='personnel'),
        ),
    ]
