# Generated by Django 5.0 on 2024-02-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_personnel_personnel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personnel',
            name='personnel',
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.UniqueConstraint(fields=('name', 'title'), name='personnel_name_title_uniq'),
        ),
    ]
