# Generated by Django 5.0 on 2024-02-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_personnel_personnel_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personnel',
            name='personnel_name_title_uniq',
        ),
    ]
