# Generated by Django 5.0 on 2024-02-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_personnel_personnel_name_title_uniq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CotabatoAuthorizedPersons',
        ),
        migrations.DeleteModel(
            name='DavaoAuthorizedPersons',
        ),
        migrations.DeleteModel(
            name='NegrosAuthorizedPersons',
        ),
        migrations.DeleteModel(
            name='SurigaoAuthorizedPersons',
        ),
    ]
