# Generated by Django 5.0 on 2024-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_cotabatoauthorizedpersons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
