# Generated by Django 5.0 on 2024-02-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_personnel_default'),
        ('main', '0007_personnel_default'),
    ]

    operations = [
    ]
